#This file stores configuration options for Iris, such as the currently active shaderpack
#Tue Dec 03 13:19:25 EST 2024
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=
