#This file stores configuration options for Iris, such as the currently active shaderpack
<<<<<<< Updated upstream
#Tue Dec 03 13:19:25 EST 2024
=======
#Sun Nov 24 15:49:37 EST 2024
>>>>>>> Stashed changes
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=
