[chicken_farm]
	#The time in ticks the chicken farm takes to spawn a chicken
	# Default: 60
	# Range: 60 ~ 60
	spawn_time = 60

[cod_farm]
	#The time in ticks the cod farm takes to spawn a cod
	# Default: 60
	# Range: 60 ~ 60
	spawn_time = 60

[cow_farm]
	#The time in ticks the cow farm takes to spawn a cow
	# Default: 60
	# Range: 60 ~ 60
	spawn_time = 60

[glow_squid_farm]
	#The time in ticks the glow squid farm takes to spawn a glow squid
	# Default: 60
	# Range: 60 ~ 60
	spawn_time = 60

[horse_farm]
	#The time in ticks the horse farm takes to spawn a horse
	# Default: 60
	# Range: 60 ~ 60
	spawn_time = 60

[mooshroom_farm]
	#The time in ticks the mooshroom farm takes to spawn a mooshroom
	# Default: 60
	# Range: 60 ~ 60
	spawn_time = 60

[parrot_farm]
	#The time in ticks the parrot farm takes to spawn a parrot
	# Default: 60
	# Range: 60 ~ 60
	spawn_time = 60

[pig_farm]
	#The time in ticks the pig farm takes to spawn a pig
	# Default: 60
	# Range: 60 ~ 60
	spawn_time = 60

[pufferfish_farm]
	#The time in ticks the pufferfish farm takes to spawn a pufferfish
	# Default: 60
	# Range: 60 ~ 60
	spawn_time = 60

[rabbit_farm]
	#The time in ticks the rabbit farm takes to spawn a rabbit
	# Default: 60
	# Range: 60 ~ 60
	spawn_time = 60

[salmon_farm]
	#The time in ticks the salmon farm takes to spawn a salmon
	# Default: 60
	# Range: 60 ~ 60
	spawn_time = 60

[sheep_farm]
	#The time in ticks the sheep farm takes to spawn a sheep
	# Default: 60
	# Range: 60 ~ 60
	spawn_time = 60

[snow_golem_farm]
	#The time in ticks the snow golem farm takes to spawn a snow golem
	# Default: 60
	# Range: 60 ~ 60
	spawn_time = 60

[squid_farm]
	#The time in ticks the squid farm takes to spawn a squid
	# Default: 60
	# Range: 60 ~ 60
	spawn_time = 60

[strider_farm]
	#The time in ticks the strider farm takes to spawn a strider
	# Default: 60
	# Range: 60 ~ 60
	spawn_time = 60

[tropical_fish_farm]
	#The time in ticks the tropical fish farm takes to spawn a tropical fish
	# Default: 60
	# Range: 60 ~ 60
	spawn_time = 60

[turtle_farm]
	#The time in ticks the turtle farm takes to spawn a turtle
	# Default: 60
	# Range: 60 ~ 60
	spawn_time = 60

[enderman_farm]
	#The time in ticks the enderman farm takes to spawn an enderman
	# Default: 60
	# Range: 60 ~ 60
	spawn_time = 60

[goat_farm]
	#The time in ticks the goat farm takes to spawn a goat
	# Default: 60
	# Range: 60 ~ 60
	spawn_time = 60

[iron_golem_farm]
	#The time in ticks the iron farm takes to spawn an iron golem
	# Default: 60
	# Range: 60 ~ 60
	spawn_time = 60

[piglin_farm]
	#The time in ticks the piglin farm takes to spawn a piglin
	# Default: 60
	# Range: 60 ~ 60
	spawn_time = 60

[spider_farm]
	#The time in ticks the spider farm takes to spawn a spider
	# Default: 60
	# Range: 60 ~ 60
	spawn_time = 60

[zombified_piglin_farm]
	#The time in ticks the zombified piglin farm takes to spawn a zombified piglin
	# Default: 60
	# Range: 60 ~ 60
	spawn_time = 60

[blaze_farm]
	#The time in ticks the blaze farm takes to spawn a blaze
	# Default: 60
	# Range: 60 ~ 60
	spawn_time = 60

[creeper_farm]
	#The time in ticks the creeper farm takes to spawn a creeper
	# Default: 60
	# Range: 60 ~ 60
	spawn_time = 60

[drowned_farm]
	#The time in ticks the drowned farm takes to spawn a drowned
	# Default: 60
	# Range: 60 ~ 60
	spawn_time = 60

[elder_guardian_farm]
	#The time in ticks the elder guardian farm takes to spawn an elder guardian
	# Default: 60
	# Range: 60 ~ 60
	spawn_time = 60

[evoker_farm]
	#The time in ticks the evoker farm takes to spawn an evoker
	# Default: 60
	# Range: 60 ~ 60
	spawn_time = 60

[ghast_farm]
	#The time in ticks the ghast farm takes to spawn a ghast
	# Default: 60
	# Range: 60 ~ 60
	spawn_time = 60

[guardian_farm]
	#The time in ticks the guardian farm takes to spawn a guardian
	# Default: 60
	# Range: 60 ~ 60
	spawn_time = 60

[hoglin_farm]
	#The time in ticks the hoglin farm takes to spawn a hoglin
	# Default: 60
	# Range: 60 ~ 60
	spawn_time = 60

[illusioner_farm]
	#The time in ticks the illusioner farm takes to spawn an illusioner
	# Default: 60
	# Range: 60 ~ 60
	spawn_time = 60

[magma_cube_farm]
	#The time in ticks the magma cube farm takes to spawn a magma cube
	# Default: 60
	# Range: 60 ~ 60
	spawn_time = 60

[phantom_farm]
	#The time in ticks the phantom farm takes to spawn a phantom
	# Default: 60
	# Range: 60 ~ 60
	spawn_time = 60

[pillager_farm]
	#The time in ticks the pillager farm takes to spawn a pillager
	# Default: 60
	# Range: 60 ~ 60
	spawn_time = 60

[ravager_farm]
	#The time in ticks the ravager farm takes to spawn a ravager
	# Default: 60
	# Range: 60 ~ 60
	spawn_time = 60

[shulker_farm]
	#The time in ticks the shulker farm takes to spawn a shulker
	# Default: 60
	# Range: 60 ~ 60
	spawn_time = 60

[skeleton_farm]
	#The time in ticks the skeleton farm takes to spawn a skeleton
	# Default: 60
	# Range: 60 ~ 60
	spawn_time = 60

[slime_farm]
	#The time in ticks the slime farm takes to spawn a slime
	# Default: 60
	# Range: 60 ~ 60
	spawn_time = 60

[vex_farm]
	#The time in ticks the vex farm takes to spawn a vex
	# Default: 60
	# Range: 60 ~ 60
	spawn_time = 60

[vindicator_farm]
	#The time in ticks the vindicator farm takes to spawn a vindicator
	# Default: 60
	# Range: 60 ~ 60
	spawn_time = 60

[warden_farm]
	#The time in ticks the warden farm takes to spawn a warden
	# Default: 60
	# Range: 60 ~ 60
	spawn_time = 60

[witch_farm]
	#The time in ticks the witch farm takes to spawn a witch
	# Default: 60
	# Range: 60 ~ 60
	spawn_time = 60

[wither_skeleton_farm]
	#The time in ticks the wither skeleton farm takes to spawn a wither skeleton
	# Default: 60
	# Range: 60 ~ 60
	spawn_time = 60

[zoglin_farm]
	#The time in ticks the zoglin farm takes to spawn a zoglin
	# Default: 60
	# Range: 60 ~ 60
	spawn_time = 60

[zombie_farm]
	#The time in ticks the zombie farm takes to spawn a zombie
	# Default: 60
	# Range: 60 ~ 60
	spawn_time = 60

[villager]
	#If the villager reputation should be the same for every player
	#This affects the prices of cured/converted villagers and the prices of the auto trader
	universal_reputation = true

[creaking_farm]
	#The time in ticks the creaking farm takes to spawn a creaking
	# Default: 60
	# Range: 60 ~ 60
	spawn_time = 60
